### ISSUE TITLE
Gulp not building

### ISSUE THREAD

**Issue by HackPoint** [ghpabs/angular2-seed#1]
**Error stack**

```
$ gulp build serve --dev
[13:45:57] Using gulpfile C:\Dev\test\gulpfile.js
C:\Users\Genad_000\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Genad_000\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by ghpabs** [comment]
Have you got `Gulp4` installed globally? Instructions can be found [here](http://blog.reactandbethankful.com/posts/2015/05/01/how-to-install-gulp-4/).
