### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by HackPoint** [ghpabs/angular2-seed#2]
```
[16:02:58] Using gulpfile C:\Dev\buybe4me\gulpfile.js
[16:02:58] Starting 'build'...
[16:02:58] Starting 'serve'...
[16:02:58] Starting 'clean'...
[16:02:58] Starting 'parallel'...
[16:02:58] Starting 'watch'...
[16:02:58] Starting 'livereload'...
[16:02:59] Server started http://localhost:8080
[16:02:59] LiveReload started on port 35729
[16:02:59] Finished 'clean' after 230 ms
[16:02:59] Starting 'parallel'...
[16:02:59] Starting 'lesslint'...
[16:02:59] Starting 'tslint'...
[16:02:59] 'tslint' errored after 296 ms
[16:02:59] TypeError: Cannot read property 'kind' of undefined
    at isStatementBraced (C:\Dev\buybe4me\node_modules\tslint\lib\rules\curlyRule.js:77:16)
    at CurlyWalker.visitDoStatement (C:\Dev\buybe4me\node_modules\tslint\lib\rules\curlyRule.js:60:14)
    at CurlyWalker.SyntaxWalker.visitNode (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:278:22)
    at C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:440:63
    at visitEachNode (C:\Dev\buybe4me\node_modules\typescript\lib\typescript.js:6833:30)
    at Object.forEachChild (C:\Dev\buybe4me\node_modules\typescript\lib\typescript.js:6988:24)
    at CurlyWalker.SyntaxWalker.walkChildren (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:440:12)
    at CurlyWalker.SyntaxWalker.visitNode (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:434:22)
    at C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:440:63
    at visitNode (C:\Dev\buybe4me\node_modules\typescript\lib\typescript.js:6821:20)
    at Object.forEachChild (C:\Dev\buybe4me\node_modules\typescript\lib\typescript.js:6909:21)
    at CurlyWalker.SyntaxWalker.walkChildren (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:440:12)
    at CurlyWalker.SyntaxWalker.visitConstructorDeclaration (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:51:14)
    at CurlyWalker.SyntaxWalker.visitNode (C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:263:22)
    at C:\Dev\buybe4me\node_modules\tslint\lib\language\walker\syntaxWalker.js:440:63
    at visitEachNode (C:\Dev\buybe4me\node_modules\typescript\lib\typescript.js:6833:30)
```

**Comment by ghpabs** [comment]
It can be fixed by running:

`$ npm install tslint@next --save-dev`

I've seen this issue before. For some reason `tslint` isn't getting installed as it should. I'll take a look further into it later on.

**Comment by ghpabs** [comment]
I've raised an issue with the `gulp-tslint` guys.

See https://github.com/panuhorsmalahti/gulp-tslint/issues/47

I'll update our `package.json` once it's been fixed. For now use the command above.

**Comment by HackPoint** [comment]
It's still don't work

Best Regards 
Genady Shmunik

**Comment by ghpabs** [comment]
Did you get any error messages after running `$ npm install tslint@next --save-dev`?

Also; when you run `$ gulp build` do you still get the error `[16:02:59] TypeError: Cannot read property 'kind' of undefined`?

**Comment by ghpabs** [comment]
Fixed.
