### ISSUE TITLE
fresh clone, `gulp build serve` error

### ISSUE THREAD

**Issue by NathanWalker** [ghpabs/angular2-seed#32]
I just cloned and ran `npm install`, then tried to `gulp build serve` and got this:

```
/Users/nathanbackup/.node/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/nathanbackup/.node/lib/node_modules/gulp/bin/gulp.js:129:19
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

```
NRWMacBook:angular2-seed-1 nathanbackup$ node --version
v4.2.2
NRWMacBook:angular2-seed-1 nathanbackup$ npm --version
2.14.7
NRWMacBook:angular2-seed-1 nathanbackup$ gulp --version
[16:32:49] CLI version 3.9.0
[16:32:49] Local version 4.0.0-alpha.2
```

**Comment by NathanWalker** [comment]
Using the locally installed version explicitly worked, nvm:
```
./node_modules/gulp/bin/gulp.js build serve
```

**Comment by ghpabs** [comment]
I'm glad you managed to find the answer. This project requires Gulp 4 to be installed globally (or you can run the local version as you did).

I'll add it to `README.md` under **Requirements**.
