### ISSUE TITLE
build issue:

### ISSUE THREAD

**Issue by Hack-Point** [ghpabs/angular2-seed#35]
$ gulp build serve                                                                                                                               
[14:10:48] Using gulpfile C:\Dev\angular2-seed\gulpfile.js                                                                                       
[14:10:48] Starting 'build'...                                                                                                                   
[14:10:48] Starting 'serve'...                                                                                                                   
[14:10:48] Starting 'clean'...                                                                                                                   
[14:10:48] Starting 'parallel'...                                                                                                                
[14:10:48] Starting 'watch'...                                                                                                                   
[14:10:48] Starting 'livereload'...                                                                                                              
[14:10:48] Server started http://localhost:8080                                                                                                  
[14:10:48] LiveReload started on port 35729                                                                                                      
[14:10:48] Finished 'clean' after 186 ms                                                                                                         
[14:10:48] Starting 'parallel'...                                                                                                                
[14:10:48] Starting 'scsslint'...                                                                                                                
[14:10:48] Starting 'tslint'...                                                                                                                  
[14:10:48] 'scsslint' errored after 266 ms                                                                                                       
[14:10:48] TypeError: Cannot read property 'start' of undefined                                                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                                 
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                                
    at Array.forEach (native)                                                                                                                    
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                                   
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                         
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)                  
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)                 
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                                
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                           
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)                    
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                            
[14:10:48] 'parallel' errored after 272 ms                                                                                                       
[14:10:48] TypeError: Cannot read property 'start' of undefined                                                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                                 
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                                
    at Array.forEach (native)                                                                                                                    
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                                   
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                         
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)                  
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)                 
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                                
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                           
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)                    
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                            
[14:10:48] 'build' errored after 467 ms                                                                                                          
[14:10:48] TypeError: Cannot read property 'start' of undefined                                                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                                  
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                                   
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                                 
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                                
    at Array.forEach (native)                                                                                                                    
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                                   
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                         
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)                  
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)                 
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                                
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                           
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)                    
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                            
[14:10:48] The following tasks did not complete: serve, parallel, watch, livereload, tslint                                                      
[14:10:48] Did you forget to signal async completion?

**Comment by Hack-Point** [comment]
and e2e tests not working

**Comment by ghpabs** [comment]
Looks like you didn't run `$ npm install` since you updated the project.

For the e2e tests, please open a different issue.

**Comment by ghpabs** [comment]
E2E tests are now fixed.
