### ISSUE TITLE
gulp build --dev not working 

### ISSUE THREAD

**Issue by Hack-Point** [ghpabs/angular2-seed#38]
after i got the latest ver.
ran npm install
ran gulp build --dev

```
$ gulp build --dev                                                                                                                       
[17:47:40] Using gulpfile C:\Dev\angular2-seed\gulpfile.js                                                                               
[17:47:41] Starting 'build'...                                                                                                           
[17:47:41] Starting 'clean'...                                                                                                           
[17:47:41] Finished 'clean' after 12 ms                                                                                                  
[17:47:41] Starting 'parallel'...                                                                                                        
[17:47:41] Starting 'scsslint'...                                                                                                        
[17:47:41] Starting 'tslint'...                                                                                                          
[17:47:41] 'scsslint' errored after 362 ms                                                                                               
[17:47:41] TypeError: Cannot read property 'start' of undefined                                                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                         
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                        
    at Array.forEach (native)                                                                                                            
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                           
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                 
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)          
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)         
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                        
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                   
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)            
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                    
[17:47:41] 'parallel' errored after 365 ms                                                                                               
[17:47:41] TypeError: Cannot read property 'start' of undefined                                                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                         
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                        
    at Array.forEach (native)                                                                                                            
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                           
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                 
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)          
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)         
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                        
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                   
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)            
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                    
[17:47:41] 'build' errored after 382 ms                                                                                                  
[17:47:41] TypeError: Cannot read property 'start' of undefined                                                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)                                          
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)                                           
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)                         
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27                                                                        
    at Array.forEach (native)                                                                                                            
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)                                           
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)                                 
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)          
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)         
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)                                        
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)                                   
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)            
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)                    
[17:47:41] The following tasks did not complete: tslint                                                                                  
[17:47:41] Did you forget to signal async completion?                                                                                    
```

**Comment by ghpabs** [comment]
I'll try to reproduce it later on tonight. Thanks.

**Comment by Hack-Point** [comment]
Sorry I don't know how.

**Comment by ghpabs** [comment]
No problem. You can format you code by opening and closing it using the triple back quote. ```

**Comment by ghpabs** [comment]
What's your `node` and `npm` versions?

**Comment by ghpabs** [comment]
Okay, I think I see what's happening. It might be somehow related to this: See https://github.com/sasstools/sass-lint/issues/62.

For now, try updating the `.scss` file and saving it again.

**Comment by ghpabs** [comment]
Please update the code base and try it again.
