### ISSUE TITLE
gulp build serve --dev

### ISSUE THREAD

**Issue by Hack-Point** [ghpabs/angular2-seed#39]
$ gulp build serve --dev
[17:51:37] Using gulpfile C:\Dev\angular2-seed\gulpfile.js
[17:51:37] Starting 'build'...
[17:51:37] Starting 'serve'...
[17:51:37] Starting 'clean'...
[17:51:37] Starting 'parallel'...
[17:51:37] Starting 'watch'...
[17:51:37] Starting 'livereload'...
[17:51:38] Server started http://localhost:8080
[17:51:38] LiveReload started on port 35729
[17:51:38] Finished 'clean' after 187 ms
[17:51:38] Starting 'parallel'...
[17:51:38] Starting 'scsslint'...
[17:51:38] Starting 'tslint'...
[17:51:38] 'scsslint' errored after 280 ms
[17:51:38] TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)
[17:51:38] 'parallel' errored after 284 ms
[17:51:38] TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)
[17:51:38] 'build' errored after 482 ms
[17:51:38] TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at Object.module.exports.detect (C:\Dev\angular2-seed\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Dev\angular2-seed\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Dev\angular2-seed\node_modules\sass-lint\index.js:43:11)
    at DestroyableTransform._transform (C:\Dev\angular2-seed\node_modules\gulp-sass-lint\index.js:38:27)
    at DestroyableTransform.Transform._read (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:333:12)
    at writeOrBuffer (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_writable.js:246:11)
    at DestroyableTransform.ondata (C:\Dev\angular2-seed\node_modules\readable-stream\lib\_stream_readable.js:581:20)
[17:51:38] The following tasks did not complete: serve, parallel, watch, livereload, tslint
[17:51:38] Did you forget to signal async completion?

**Comment by ghpabs** [comment]
Duplicated https://github.com/ghpabs/angular2-seed/issues/38
