### ISSUE TITLE
gulp build serve : Problem

### ISSUE THREAD

**Issue by maxime1992** [ghpabs/angular2-seed#5]
I'm wondering what i missed here.
I ran `npm install`, it's ok.
I ran `gulp build`, no problem.
When i run `gulp build serve` i get the following error :

```shell
maxime@maxime:~/Documents/perso/angular2-seed$ gulp build serve
[22:44:29] Using gulpfile ~/Documents/perso/angular2-seed/gulpfile.js
[22:44:29] Starting 'build'...
[22:44:29] Starting 'serve'...
[22:44:29] Starting 'clean'...
[22:44:29] Starting 'parallel'...
[22:44:29] Starting 'watch'...
[22:44:29] Starting 'livereload'...
[22:44:29] Server started http://localhost:8080
[22:44:29] LiveReload started on port 35729
[22:44:29] 'watch' errored after 250 ms
[22:44:29] Error: watch src/index.html ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
[22:44:29] 'parallel' errored after 262 ms
[22:44:29] Error: watch src/index.html ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
[22:44:29] 'serve' errored after 265 ms
[22:44:29] Error: watch src/index.html ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/home/maxime/Documents/perso/angular2-seed/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
[22:44:29] The following tasks did not complete: build, clean, livereload
[22:44:29] Did you forget to signal async completion?```

**Comment by maxime1992** [comment]
Ok ... After deleting two times the node_modules folder and reinstalled all the deps with `npm install`, it finally worked.

I don't get it. For those who might get this error, a fix seems to run this :
```shell
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
(source : http://stackoverflow.com/a/17437601/2398593)

**Comment by ghpabs** [comment]
Interesting issue. I didn't even know file watcher limit was a thing.

Thanks for documenting it.
